### ISSUE TITLE
AWS Fargate Server Consistently Returns 503

### ISSUE THREAD

**Issue by mark-antony1** [tonyfromundefined/prisma-aws-cloudformation#4]
Hello,

I went through the `https://www.prisma.io/tutorials/deploy-prisma-to-aws-fargate-ct14` guide a few times, and while both my RDS and Fargate instance have been created successfully, when i try to access the `external url` for the Fargate instance i get a 503.

When I try to access the Fargate instance with `prisma deploy` on a EC2 instance with security permissions. I always get a 503 message.

If i turn on debug mode to more information, i see several API calls and error responses in the following order.

```FetchError: invalid json response body at [AWS LINK] reason: Unexpected token < in JSON at position 0```

```
  command Failed to fetch server version +0ms
  command TypeError: Cannot read property 'replace' of null +0ms
  environment Assuming that the server needs authentication +372ms
```

```
  client Failed to add service to cloud, most likely this server is not connected to Prisma cloud +446ms
```

```
client Error: GraphQL Error (Code: 400): {"response":{"error":"<!DOCTYPE html>\n<html>\n  <head>\
```

```
Error: GraphQL Error (Code: 503): {"response":{"error":"<html>\r\n<head><title>503 Service Temporarily Unavailable
```

**Comment by tonyfromundefined** [comment]
It is because the timing issue. this cloudformation template resolve that issue by
https://github.com/tonyfromundefined/prisma-aws-cloudformation/blob/master/prisma.mysql.yml#L389
